# Generated by Django 6.0.7 on 2026-08-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='purpose',
            field=models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('CHANGE_EMAIL', 'Change Email')], max_length=20),
        ),
    ]
